version: '3.4'

networks:
  employeemanagementapi:
   
services:
  employeedb:
    container_name: employeedb
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
     - 8002:1433
    environment:
     - ACCEPT_EULA=Y
     - MSSQL_SA_PASSWORD=Password@123#
    networks:
     - employeemanagementapi
     

  employeemanagement.api:
    image: ${DOCKER_REGISTRY-}employeemanagementapi
    build:
      context: .
      dockerfile: EmployeeManagement.API/Dockerfile
    ports:
      - 9500:8080
    depends_on:
     - employeedb
    environment:
     - DB_HOST=employeedb
     - DB_NAME=YODB
     - DB_USER=sa
     - DB_PASSWORD=Password@123#
    networks:
     - employeemanagementapi
